/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CongressRouteImport } from './routes/congress'
import { Route as EnvoysRouteImport } from './routes/envoys'
import { Route as ExposureRouteImport } from './routes/exposure'
import { Route as MilitaryRouteImport } from './routes/military'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WatchRouteImport } from './routes/watch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CongressRoute = CongressRouteImport.update({
  id: '/congress',
  path: '/congress',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvoysRoute = EnvoysRouteImport.update({
  id: '/envoys',
  path: '/envoys',
  getParentRoute: () => rootRouteImport,
} as any)
const ExposureRoute = ExposureRouteImport.update({
  id: '/exposure',
  path: '/exposure',
  getParentRoute: () => rootRouteImport,
} as any)
const MilitaryRoute = MilitaryRouteImport.update({
  id: '/military',
  path: '/military',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/congress': typeof CongressRoute
  '/envoys': typeof EnvoysRoute
  '/exposure': typeof ExposureRoute
  '/military': typeof MilitaryRoute
  '/sources': typeof SourcesRoute
  '/timeline': typeof TimelineRoute
  '/watch': typeof WatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/congress': typeof CongressRoute
  '/envoys': typeof EnvoysRoute
  '/exposure': typeof ExposureRoute
  '/military': typeof MilitaryRoute
  '/sources': typeof SourcesRoute
  '/timeline': typeof TimelineRoute
  '/watch': typeof WatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/congress': typeof CongressRoute
  '/envoys': typeof EnvoysRoute
  '/exposure': typeof ExposureRoute
  '/military': typeof MilitaryRoute
  '/sources': typeof SourcesRoute
  '/timeline': typeof TimelineRoute
  '/watch': typeof WatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/congress'
    | '/envoys'
    | '/exposure'
    | '/military'
    | '/sources'
    | '/timeline'
    | '/watch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/congress'
    | '/envoys'
    | '/exposure'
    | '/military'
    | '/sources'
    | '/timeline'
    | '/watch'
  id:
    | '__root__'
    | '/'
    | '/congress'
    | '/envoys'
    | '/exposure'
    | '/military'
    | '/sources'
    | '/timeline'
    | '/watch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CongressRoute: typeof CongressRoute
  EnvoysRoute: typeof EnvoysRoute
  ExposureRoute: typeof ExposureRoute
  MilitaryRoute: typeof MilitaryRoute
  SourcesRoute: typeof SourcesRoute
  TimelineRoute: typeof TimelineRoute
  WatchRoute: typeof WatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congress': {
      id: '/congress'
      path: '/congress'
      fullPath: '/congress'
      preLoaderRoute: typeof CongressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envoys': {
      id: '/envoys'
      path: '/envoys'
      fullPath: '/envoys'
      preLoaderRoute: typeof EnvoysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exposure': {
      id: '/exposure'
      path: '/exposure'
      fullPath: '/exposure'
      preLoaderRoute: typeof ExposureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/military': {
      id: '/military'
      path: '/military'
      fullPath: '/military'
      preLoaderRoute: typeof MilitaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CongressRoute: CongressRoute,
  EnvoysRoute: EnvoysRoute,
  ExposureRoute: ExposureRoute,
  MilitaryRoute: MilitaryRoute,
  SourcesRoute: SourcesRoute,
  TimelineRoute: TimelineRoute,
  WatchRoute: WatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
